### ISSUE TITLE
Brand Name not being applied

### ISSUE THREAD

**Issue by johnbeadle** [johnbeadle/CordovaMessagingSDKSample#18]
The ‘brand_name’ option doesn’t seem to be taking effect on Android.
 
We have in the branding.xml file the following line...
 
`<string name='brand_name'>Message us</string>`

![image](https://user-images.githubusercontent.com/10999907/26888231-424b6e78-4ba2-11e7-9ab5-c20f336a0b61.png)

**Comment by johnbeadle** [comment]
@drewzh Here is the solution...you need to create Android resource files for each language your app supports - including english!

![screen shot 2017-06-08 at 18 06 28](https://user-images.githubusercontent.com/10999907/26941263-bf355a74-4c75-11e7-815b-2efc65c62349.png)

The above `strings.xml` file shows the brand name being changed in sample app 03...

Please apply to your app and confirm this fixes the brand name issue.

**Comment by drewzh** [comment]
I'll be applying this fix today. Thanks @johnbeadle

**Comment by johnbeadle** [comment]
@drewzh can you confirm is this fix has been applied and is working please? We need to let internal Support know if it has been successful or not. Thanks.

**Comment by johnbeadle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Android - Brand name editing](https://trello.com/c/IMnmJP79/43-android-brand-name-editing)

**Comment by drewzh** [comment]
I can confirm the string file modifications are working for the brand_name issue. Thanks John
