### ISSUE TITLE
TTR Out of Hours Toaster not disappearing when shift resumes / agent replies / conversation starts

### ISSUE THREAD

**Issue by johnbeadle** [johnbeadle/CordovaMessagingSDKSample#22]
## Behaviour Both platforms...

If a customer starts a new conversation when the shift is set to OUT OF HOURS and agents are OFFLINE, then `offHoursBanner` is shown in the conversation window with the details when the next shift will start...

However, if that is e.g. 1 hr in the future and then the shift is changed back to ONLINE, the toaster does not disappear even if a conversation begins and is accepted.

![screen shot 2017-06-09 at 12 50 57](https://user-images.githubusercontent.com/10999907/26975880-95084bd6-4d19-11e7-9ab9-c475ba55b9a2.png)

## iOS

+ Even after the cached shift online time as passed, the toaster banner still remains on iOS.
+ Seemingly the only way to make it disappear is to close and re-open the conversation screen AFTER the start time has passed
+ Or "mark as urgent" which causes the toaster to be refreshed with the updated agent SLA.

**notice AFTER 1pm when messages are sent on Android the toaster disappears, but iOS it remains**

![screen shot 2017-06-09 at 13 00 34](https://user-images.githubusercontent.com/10999907/26975898-af56c86e-4d19-11e7-92c0-0f58cca619ee.png)

![screen shot 2017-06-09 at 13 44 37](https://user-images.githubusercontent.com/10999907/26975977-ebd132b6-4d19-11e7-892c-914f6cee0bf6.png)

**Comment by johnbeadle** [comment]
@drewzh FYI...

**Comment by drewzh** [comment]
Hi @johnbeadle. I'm not familiar with this but I've made the relevant parties know. Thanks for the update.

**Comment by johnbeadle** [comment]
@drewzh I can see my `LPMessagingSDKOffHoursStateChanged` eventName being triggered when it detects the shift first is offline/out of hours. The issue seems to be this is cached until it thinks the timestamp has been reached and the toaster does not disappear...

```
@@@ ios... LPMessagingSDKOffHoursStateChanged: true, 90233546
@@@ ios... LPMessagingSDKOffHoursStateChanged: true, 90233546
```

the `true` in this context means it thinks it is still `offHours` = `true`

Will continue investigation...

**Comment by johnbeadle** [comment]
Even closing an reopening the conversation screen does not close the toaster whilst it thinks it is BEFORE the previous cached timestamp for when the shift then comes back online...

```
@@@ ios... LPMessagingSDKOffHoursStateChanged: true, 90233546
@@@ iOS ... LPMessagingSDKConnectionStateChanged: true, 90233546
@@@ ios ... LPMessagingSDKConversationViewControllerDidDismiss
@@@ iOS ... LPMessagingSDKConnectionStateChanged: false, 90233546
...reopen the window...
@@@ LPMessagingSDKStartConversation conversationType : authenticated
@@@ iOS ... LPMessagingSDKConnectionStateChanged: false, 90233546
@@@ ios... LPMessagingSDKOffHoursStateChanged: true, 90233546
@@@ iOS ... LPMessagingSDKConnectionStateChanged: true, 90233546
```

essentially still thinks the shift is offline as the online timestamp has not yet been reached!

**Comment by johnbeadle** [comment]
Once the TTR off hours window passes on iOS, another message sent from the customer triggers the callback and the toaster disappears...

```
@@@ iOS ... LPMessagingSDKConnectionStateChanged: true, 90233546
@@@ ios... LPMessagingSDKOffHoursStateChanged: false, 90233546
```

**Comment by johnbeadle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [iOS Toaster for TTR offline hours](https://trello.com/c/6AmDVjH3/41-ios-toaster-for-ttr-offline-hours)

**Comment by johnbeadle** [comment]
According to internal sources, apparently this resolved in SDK 2.3.... TBC and tested but unlikely to have any workaround/fix with v2.1.5

**Comment by drewzh** [comment]
Thanks John, I've updated our internal issue tracker with a note to re-test.

**Comment by johnbeadle** [comment]
@drewzh further investigations show this behaviour still exists in 2.5

However, I have learned it is not a bug in the SDK itself, but with the information logic happening server side which is giving the SDK it's data for this toaster etc.

So the resolution will require a much bigger fix on our platform side to resolve. This is known and is being prioritised but for now this will not be fixed in the near future, or with this version as it is not where the problem lies
