### ISSUE TITLE
[iOS] Sometimes UI will not show new messages

### ISSUE THREAD

**Issue by drewzh** [johnbeadle/CordovaMessagingSDKSample#72]
I'm not sure if this is platform specific, but after leaving the messaging UI open for an hour whilst I was away from my desk, when I returned I've noticed that no new messages are displaying for the user, although messages are still sending correctly. Unfortunately, for this issue, I'm unable to produce logs as it's a non-debugging release signed app.

When this issue occurs, the user is able to send new messages that are received on the agent side, but the UI doesn't update to show these newly sent messages.

Events, such as when the agent or user are currently typing are still occurring and the UI updates accordingly on both sides when a new messages are being composed.

**Comment by johnbeadle** [comment]
@drewzh 
what is the expiration time of your JWT set to?
what is sub for this particular test session in the clone account?
Are you able to reproduce on the simulator with logs?

**Comment by drewzh** [comment]
Unfortunately, the only information I have access to is the sub (which I'll message you details of on Slack). In regards to specific JWT details, this is all hidden from me.

This is using the live environment/account.

Nobody on our side has seen this issue before now so I imagine it's quite a fringe bug, but thought it's worth mentioning nether the less.

I'll keep an eye out to see if this occurs again and if possible, produce logs etc.

**Comment by johnbeadle** [comment]
closing issue...if still prevalent will resolve in future plugin/SDK updates
