### ISSUE TITLE
Hyperlink issue when number prefixed with 0

### ISSUE THREAD

**Issue by drewzh** [johnbeadle/CordovaMessagingSDKSample#76]
Re-raised from https://github.com/LivePersonInc/CordovaMessagingSDKSample/issues/7

lakshmivenkobarao commented 7 days ago
In Android, if user/agent prefix mobile number with 0 in messages, then the number will not be hyperlinked. Please refer screenshot

![](https://user-images.githubusercontent.com/29858414/27787309-392cc2d0-5fdc-11e7-9c46-854d0d320477.png)

![](https://user-images.githubusercontent.com/29858414/27787310-392ea87a-5fdc-11e7-84ae-0d6ce794200b.png)

**Comment by johnbeadle** [comment]
@drewzh please confirm SDK version applicable? 2.1.5 or 2.5?

**Comment by johnbeadle** [comment]
closing. confirmed for 2.1.5 and fixed on 2.5

SDK applies different regex depending on device regional settings. US setting = US phone number format regex.
