### ISSUE TITLE
getNumUnreadMessages always returns 0

### ISSUE THREAD

**Issue by drewzh** [johnbeadle/CordovaMessagingSDKSample#79]
The `getNumUnreadMessages` API available in 2.5.0 doesn't seem to function how we'd expect? Maybe there's an extra detail that we're unaware of, but the method always returns 0.

```java
    private int getUnreadMessageCount(String accountId) {
        return LivePerson.getNumUnreadMessages(accountId);
    }
```

I've tried calling this whilst the message screen is closed and the customer has multiple unread messages and also when the application is sent into the background and push notifications are being received.

https://github.com/LP-Messaging/Android-Messaging-SDK/blob/2.3.0/Documentation/In-app%20Messaging%20SDK%20v2.3.0%20Release%20Notes-Android.pdf

**Comment by johnbeadle** [comment]
@drewzh as per the PDF you linked to....

![image](https://user-images.githubusercontent.com/10999907/28094372-13abc45c-6694-11e7-829a-3bf8ccbc6a20.png)


https://github.com/LP-Messaging/Android-Messaging-SDK/blob/9383b9c82963e7cc1c89b8dcc00c534ed056214a/SampleApp-Source/sample_app/src/main/java/com/liveperson/sample/app/push/fcm/MyFirebaseMessagingService.java#L48

```java
	/**
	 * Called when message is received.
	 *
	 * @param remoteMessage Object representing the message received from Firebase Cloud Messaging.
	 */
	// [START receive_message]
	@Override
	public void onMessageReceived(RemoteMessage remoteMessage) {
		// [START_EXCLUDE]
		// There are two types of messages data messages and notification messages. Data messages are handled
		// here in onMessageReceived whether the app is in the foreground or background. Data messages are the type
		// traditionally used with GCM. Notification messages are only received here in onMessageReceived when the app
		// is in the foreground. When the app is in the background an automatically generated notification is displayed.
		// When the user taps on the notification they are returned to the app. Messages containing both notification
		// and data payloads are treated as notification messages. The Firebase console always sends notification
		// messages. For more see: https://firebase.google.com/docs/cloud-messaging/concept-options
		// [END_EXCLUDE]

		// TODO(developer): Handle FCM messages here.
		// Not getting messages here? See why this may be: https://goo.gl/39bRNJ
		Log.d(TAG, "From: " + remoteMessage.getFrom());

		// Check if message contains a data payload.
		if (remoteMessage.getData().size() > 0) {
			Log.d(TAG, "Message data payload: " + remoteMessage.getData());

			// Send the data into the SDK
			String account = SampleAppStorage.getInstance(this).getAccount();
			PushMessage message = LivePerson.handlePushMessage(this, remoteMessage.getData(), account, false);

			//Code snippet to add push UI notification
			if (message != null){
				NotificationUI.showNotification(this, message);
			}

		}

		// Check if message contains a notification payload.
		if (remoteMessage.getNotification() != null) {
			Log.d(TAG, "Message Notification Body: " + remoteMessage.getNotification().getBody());
		}

		// Also if you intend on generating your own notifications as a result of a received FCM
		// message, here is where that should be initiated. See sendNotification method below.
	}
```


https://github.com/LP-Messaging/Android-Messaging-SDK/blob/9383b9c82963e7cc1c89b8dcc00c534ed056214a/SampleApp-Source/sample_app/src/androidTest/java/com/liveperson/messagingtest/ApplicationTest.java#L64

![image](https://user-images.githubusercontent.com/10999907/28094379-1b7aac84-6694-11e7-87f5-41f3ddad3d9d.png)

https://github.com/LP-Messaging/Android-Messaging-SDK/blob/4cb5e34e52dee9df84271efbc65f7b884a9e2e33/SampleApp-Source/sample_app/src/main/java/com/liveperson/sample/app/MainActivity.java#L402

```java
IntentFilter unreadMessagesCounterFilter = new IntentFilter(LivePerson.ACTION_LP_UPDATE_NUM_UNREAD_MESSAGES_ACTION);
BroadcastReceiver unreadMessagesCounter = new BroadcastReceiver() {
    @Override
    public void onReceive(Context context, Intent intent) {
        int newValue = intent.getIntExtra(LivePerson.ACTION_LP_UPDATE_NUM_UNREAD_MESSAGES_EXTRA, 0);
        Log.d(TAG, "Got new value for unread messages counter: " + newValue);
        updateToolBar(newValue);
    }
};
```

**Comment by drewzh** [comment]
Thanks for your response John.

> Note: For the unread messages feature to work correctly, the host app must call this method
> upon receiving SDK push messages (whether showing a custom notification or not).

As we handle push notifications outside of the Live Person SDK via Firebase/Cordova plugin, on certain conditions, the application isn't made aware of a push notification.

E.g, if the user receives a push notification whilst the app is in the background and the user chooses to open the application via the launcher icon rather than clicking the notification itself, the app isn't made aware of the push notification, thus we'd be unable to run `handlePushMessage`.

Also, when the user chooses to click the notification, they are taken directly to the Live Person messaging screen, bypassing the UI where we'd show the new message indicator.

Would the intent listener method work for us instead for this scenario or does it have the same requirement of calling `handlePushMessage` to function?

Many thanks

**Comment by johnbeadle** [comment]
> Would the broadcastReceiver method work for us instead for this scenario or does it have the same requirement of calling handlePushMessage to function?

As per the above, my understanding is the host app **must call handlePushMessage** regardless if you want to be able to use the `broadcastReceiver` method. They are closely linked, not 2 separate options.

>As we handle push notifications outside of the Live Person SDK via Firebase/Cordova plugin, on certain conditions, the application isn't made aware of a push notification.

> E.g, if the user receives a push notification whilst the app is in the background and the user chooses to open the application via the launcher icon rather than clicking the notification itself, the app isn't made aware of the push notification, thus we'd be unable to run handlePushMessage.

Then this may well prove to be a limitation of using Cordova along with a 3rd party push plugin as opposed to doing things natively. You may not be able to leverage this feature. Only my time and effort on my side (when is TBC) will allow this to be ruled out or not.

**Comment by drewzh** [comment]
I've fed this information back. We were under the impression this was a live query of unread messages. There doesn't appear to be any additional benefit over just storing the push notification count ourselves and referencing that instead?

**Comment by sandygoria** [comment]
with regard to @johnbeadle question, we have the same implementation as -
"E.g, if the user receives a push notification whilst the app is in the background and the user chooses to open the application via the launcher icon rather than clicking the notification itself, the app isn't made aware of the push notification, thus we'd be unable to run handlePushMessage."  

so, @drewzh .. how to handle the same in pure Native Android app.

**Comment by johnbeadle** [comment]
@sandygoria for how to retrieve unread messages on Android and iOS **using pure native methods** please refer to the latest official documentation site here:

* Android => https://developers.liveperson.com/android-methods.html#getnumunreadmessages
* iOS => https://developers.liveperson.com/consumer-experience-ios-sdk-release-notes.html#unread-messages-badge

If you question is related to how this is done via Cordova plugin, one possible example is shown here from the sampleapp03 for Android within this repo:

Android .java plugin file:

* Create broadcast receiver:

https://github.com/johnbeadle/CordovaMessagingSDKSample/blob/f07bfb6a45bd0168fcc78d67679e9da5033a40d9/apps/sampleapp03/platforms/android/src/com/liveperson/plugin/LPMessagingSDK.java#L64

* Register broadcast receiver:

https://github.com/johnbeadle/CordovaMessagingSDKSample/blob/f07bfb6a45bd0168fcc78d67679e9da5033a40d9/apps/sampleapp03/platforms/android/src/com/liveperson/plugin/LPMessagingSDK.java#L108

* Setup the handling of the event for unread message

https://github.com/johnbeadle/CordovaMessagingSDKSample/blob/f07bfb6a45bd0168fcc78d67679e9da5033a40d9/apps/sampleapp03/platforms/android/src/com/liveperson/plugin/LPMessagingSDK.java#L267

* javascript callback to take action

https://github.com/johnbeadle/CordovaMessagingSDKSample/blob/f07bfb6a45bd0168fcc78d67679e9da5033a40d9/apps/sampleapp03/platforms/android/assets/www/js/index.js#L177
